### ISSUE TITLE
Issues with flit

### ISSUE THREAD

**Issue by RMeli** [RMeli/spyrmsd#54]
**Describe the bug**

PyPI action failed to deploy version `0.5.0`. The failure was confirmed locally as well, with the latest version of `flit`.

**To Reproduce**

See https://github.com/takluyver/flit/issues/415 and [actions/958636640](https://github.com/RMeli/spyrmsd/actions/runs/958636640).

**Additional Context**

Downgrading to `flit=3.1.0` works as usual.

---

Version `0.5.0` was released manually from a local workstation.

**Comment by RMeli** [comment]
Another issue with `flit` popped up in CI:
```text
Traceback (most recent call last):
        File "/usr/share/miniconda/envs/spyrmsd/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/share/miniconda/envs/spyrmsd/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/share/miniconda/envs/spyrmsd/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-fkn_rmy6/overlay/lib/python3.9/site-packages/flit_core/buildapi.py", line 49, in prepare_metadata_for_build_wheel
          metadata = make_metadata(module, ini_info)
        File "/tmp/pip-build-env-fkn_rmy6/overlay/lib/python3.9/site-packages/flit_core/common.py", line 399, in make_metadata
          md_dict.update(get_info_from_module(module, ini_info.dynamic_metadata))
        File "/tmp/pip-build-env-fkn_rmy6/overlay/lib/python3.9/site-packages/flit_core/common.py", line 196, in get_info_from_module
          docstring, version = get_docstring_and_version_via_import(target)
        File "/tmp/pip-build-env-fkn_rmy6/overlay/lib/python3.9/site-packages/flit_core/common.py", line 171, in get_docstring_and_version_via_import
          spec.loader.exec_module(m)
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line [22](https://github.com/RMeli/spyrmsd/runs/5301813393?check_suite_focus=true#step:5:22)8, in _call_with_frames_removed
        File "/home/runner/work/spyrmsd/spyrmsd/spyrmsd/__init__.py", line 5, in <module>
          from ._version import get_versions
      ModuleNotFoundError: No module named 'flit_core.dummy'
      [end of output]
```

This has already been reported and seems to affect a lot of other packages: https://github.com/pypa/flit/issues/530

**Comment by RMeli** [comment]
The problem persists as of `v0.6.0`:

```
Fetching list of valid trove classifiers               I-flit.validate
Found 220 files tracked in git                            I-flit.sdist
Built sdist: dist/spyrmsd-0.6.0.tar.gz               I-flit_core.sdist
Copying package file(s) from /tmp/tmpjhxovlsj/spyrmsd-0.6.0/spyrmsd  I-flit_core.wheel
Writing metadata files                               I-flit_core.wheel
Writing the record of files                          I-flit_core.wheel
Built wheel: dist/spyrmsd-0+unknown-py3-none-any.whl I-flit_core.wheel
Found 220 files tracked in git                            I-flit.sdist
Built sdist: dist/spyrmsd-0.6.0.tar.gz               I-flit_core.sdist
Copying package file(s) from /tmp/tmpo_o__9sy/spyrmsd-0.6.0/spyrmsd  I-flit_core.wheel
Writing metadata files                               I-flit_core.wheel
Writing the record of files                          I-flit_core.wheel
Built wheel: dist/spyrmsd-0+unknown-py3-none-any.whl I-flit_core.wheel
Using repository at https://upload.pypi.org/legacy/      I-flit.upload
Uploading dist/spyrmsd-0+unknown-py3-none-any.whl...     I-flit.upload
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.5/x64/bin/flit", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/flit/__init__.py", line 200, in main
    main(args.ini_file, repository, args.pypirc, formats=set(args.format or []),
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/flit/upload.py", line 277, in main
    do_upload(built.wheel.file, built.wheel.builder.metadata, pypirc_path, repo_name)
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/flit/upload.py", line 252, in do_upload
    upload_file(file, metadata, repo)
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/flit/upload.py", line 245, in upload_file
    resp.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: '0+unknown' is an invalid value for Version. Error: Can't use PEP 440 local versions. See https://packaging.python.org/specifications/core-metadata for more information. for url: https://upload.pypi.org/legacy/
```

**Comment by RMeli** [comment]
To create release `0.6.0` I manually amended
```
__version__ = "0.6.0"
```

and then

```
flit build
flit publish
```

worked as expected.

**Comment by RMeli** [comment]
Removing versioner in #91 and updating the GitHub Secrets `FLIT_USERNAME` and `FLIT_PASSWORD` to use PyPI token authentication allowed to [deploy successfully](https://github.com/RMeli/spyrmsd/actions/runs/8576130355) again using `flit`.
